checks.d/ssh_check.py usr/share/python/sd-agent/checks.d
conf.d/ssh_check.yaml.example etc/sd-agent/conf.d

debian/build/lib/python3.*/site-packages/paramiko*  usr/share/python/sd-agent/lib/python3.*/site-packages
debian/build/lib/python3.*/site-packages/cryptography*  usr/share/python/sd-agent/lib/python3.*/site-packages
debian/build/lib/python3.*/site-packages/Crypto*  usr/share/python/sd-agent/lib/python3.*/site-packages
debian/build/lib/python3.*/site-packages/cffi* usr/share/python/sd-agent/lib/python3.*/site-packages
debian/build/lib/python3.*/site-packages/pycparser* usr/share/python/sd-agent/lib/python3.*/site-packages
